[build]
builder = "dockerfile"

[[services]]
id = "backend"
path = "backend"

[services.build]
buildCommand = "python manage.py collectstatic --noinput"

[[services]]
id = "frontend"
path = "frontend"